yolo_model:

  config_file:
    name: third.cfg
  weight_file:
    name: third.weights
  threshold:
    value: 0.7
  detection_classes:
    names:
      - G
      - R
      - LG
      - LR
      - Y
      - A1
      - A2
      - A3
      - B1
      - B2
      - B3
      
